field: 17851753-f1d6-4912-ae96-0e4377bab354 # Inhoud
fieldLayouts:
  3195b9d0-44c5-4fd0-a229-6554f5e17a88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 92ff6d7c-52e1-4490-88ab-31b8057fa459 # Embed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e636985a-438b-477a-a708-7baaaffe80e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d449ad2-b125-468b-a19d-88c178b16897
        userCondition: null
fields:
  92ff6d7c-52e1-4490-88ab-31b8057fa459: # Embed
    columnSuffix: gxeomqlc
    contentColumnType: text
    fieldGroup: null
    handle: embed
    instructions: null
    name: Embed
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: embed
name: Embed
sortOrder: 4
