field: 17851753-f1d6-4912-ae96-0e4377bab354 # Inhoud
fieldLayouts:
  a40d8fe1-591f-4bab-92d1-0e48cffd4256:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73d9b7e3-8113-4470-95cb-24e658b6e41e # Afbeelding
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c41582f-ae47-451a-8342-834d91bb33fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 577a786c-bb8b-4c30-99d1-056724995623
        userCondition: null
fields:
  73d9b7e3-8113-4470-95cb-24e658b6e41e: # Afbeelding
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Afbeelding
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
      restrictedLocationSubpath: /content/images
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Afbeelding
sortOrder: 1
