field: 17851753-f1d6-4912-ae96-0e4377bab354 # Inhoud
fieldLayouts:
  1cb64cfb-0d1b-4587-88c0-d2d79e799df3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b38b7d92-effd-4ff7-9dd7-afe36a88f42a # PDFs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f19d10e-0d9a-40e3-bb54-e5c59a3f6de7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df8d3162-44cc-45a0-88a4-b26ead6b082b
        userCondition: null
fields:
  b38b7d92-effd-4ff7-9dd7-afe36a88f42a: # PDFs
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: pdfs
    instructions: null
    name: PDFs
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
      restrictedLocationSubpath: /pdf
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: pdfs
name: PDFs
sortOrder: 6
