field: 17851753-f1d6-4912-ae96-0e4377bab354 # Inhoud
fieldLayouts:
  f09846e8-214c-4aad-9137-9bdeabef48a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8db180a8-63e8-444c-b730-7f85de2e44e0 # Tekst
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d90a8e0d-2f8f-4e9d-bf76-3b5b3ff4f693
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2dd179ed-e08e-4084-8fff-958bc0128e83 # Author
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7669b896-efb3-471f-9f3a-17e4352aaf5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed3e2d8c-741d-4de4-8719-697896f87026
        userCondition: null
fields:
  2dd179ed-e08e-4084-8fff-958bc0128e83: # Author
    columnSuffix: pkxaahai
    contentColumnType: text
    fieldGroup: null
    handle: author
    instructions: null
    name: Author
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8db180a8-63e8-444c-b730-7f85de2e44e0: # Tekst
    columnSuffix: lgnuykqw
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Tekst
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 3
