fieldLayouts:
  6734e714-ef9c-4d3a-a060-caa8e55fae2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5ed4d53d-47f9-4ce4-8db6-4e2ad4bc9583 # Sponsor Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba7f78f1-5a09-43dd-8c4a-1508c8d5cbf4
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ba6a398f-f451-4e11-83d8-5bb45ad7465c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d747c871-4db7-4d98-b9b6-d903dc0f40e9 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1fe7e2a-93be-4301-b744-a252e8b7391b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1eeda847-3fd9-49ad-a212-3ddaf25446c6 # Adres
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e54aff9-3dab-4e66-8b18-a4a9eb60725f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a45e8064-29dd-4fd9-9901-751b6330f738 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca843988-834a-4e2c-bc76-a7eb9179c6dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09c3a06f-0723-41d2-8d1e-bd59656be935
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: a4da36f1-92af-4214-bd7b-7cd817673b7c # Sponsors
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
