fieldLayouts:
  0c450daa-61cc-4d84-92cc-586922272632:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3c425068-3410-4ae9-83e6-89a993c851ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f67f9e31-79ca-4013-8959-ec0e19edbd19 # Team Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74123b5b-fd64-4007-b2f4-35d1b8ba1500
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02c80827-fed5-431b-81ca-ce8f5f560445 # Club
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8107c614-cbcc-4a38-8eff-eba20df3b533
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1396ba41-9f9d-4fdb-8788-162c7d5a11a4 # Spelers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4f79176-a0f6-4ede-8e0e-b82ccc27fdb6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 366b6352-e107-4630-9cd1-024fc3565c1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d6bd3932-17bb-492f-9ee7-2f000018ac63 # Team Foto
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92dc9148-3901-441d-b373-098b9308d24d
            userCondition: null
            warning: null
            width: 100
        name: Foto
        uid: 7e5a7002-f6fd-4286-b633-22dcef17a37f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: d23c1e7e-d9e0-4285-870f-3cb53df9f68c # Teams
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
