fieldLayouts:
  6ea5a076-d77d-4a94-9b07-cc07181a7dff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1192a1d5-820b-4265-bad9-9b292ca079db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d747c871-4db7-4d98-b9b6-d903dc0f40e9 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a3f4269-9f5b-42e2-a401-85f80e1f9bcc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 17851753-f1d6-4912-ae96-0e4377bab354 # Inhoud
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b46344d6-5f54-47cc-a1b6-5a275ab18808
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f51e996c-c08a-493b-ba1f-5a0684c6c328
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7c593917-8377-4440-b9cd-e162b99fe647 # Nieuws
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
