fieldLayouts:
  f52f99f7-525b-44b3-a6b0-10b814effe4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb9ac991-1b41-45fd-91d8-53c591dd0223
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4aa67f84-30e9-4b62-82ee-90ca0bfcd617 # Voornaam
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b9bbe05-966c-40fc-91f4-31e5bbbf38c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ccb9335-6fa4-4a02-864a-960d8ff0ed1b # Achternaam
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 844b1419-f233-45c6-93e3-71569dcd3f36
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c22497ae-186e-4442-8842-280f7287d053 # Bestuur Rol
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb7fa7ef-23b5-46f3-bcf1-d97a48250566
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 813b1092-2513-42c0-9bbc-afa50864e0bf # Telefoon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d47cdc99-4489-46c4-835f-e5d7fe546793
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c0938c6-ce88-4fe2-8bfe-b18d74017936 # E-mail
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eff85fe3-30d9-461b-962d-80716c1c8f55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e47f154-c85c-4932-9ceb-db19c6d387dd
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: ddec216d-9a35-444b-b4c7-b6b7757714fa # Bestuur
sortOrder: 1
titleFormat: '{firstName} {lastName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
