fieldLayouts:
  4384b724-54cc-4834-bfdf-92c215fb9e64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3077f0db-2f3b-4921-a074-84d98075cc00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ff642d6-eb8a-4702-ba39-d296ba3299ca
        userCondition: null
handle: newsOverview
hasTitleField: false
name: 'Nieuws (Overzicht)'
section: 340e0566-380f-4317-87f7-1088e327f13d # Nieuws (Overzicht)
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
