fieldLayouts:
  5637bcb8-2801-4bfe-9716-16dd4b6e28ce:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 95bce004-3f80-4545-b72c-269bd12929a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cedfd60e-4cf0-4a27-9123-93a290bd8bc3 # Entry Lijst
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fea6590-60a2-46a3-ad51-643641c99904
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 46b3e93a-df9c-4639-81d2-42adee465c21
        userCondition: null
handle: submenuSection
hasTitleField: true
name: 'Submenu Section'
section: 7f7bf0f5-26b9-4557-bcee-5585832b1522 # Hoofd menu
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
