fieldLayouts:
  3612e92a-8360-4947-b02d-a6ccc7cf9cfb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2347a765-e080-45b6-866e-f46ec2e64d6d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 82020a4e-134d-4123-9282-b1c52a114847
        userCondition: null
handle: teamsOverview
hasTitleField: false
name: 'Teams Overzicht'
section: dff6210f-1228-4523-8858-c711a7ff5aa6 # Teams Overzicht
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
