columnSuffix: cpnyrplf
contentColumnType: text
fieldGroup: 5fda7d6b-6c90-4033-b4c4-82005d425e44 # Competities
handle: competitionCode
instructions: null
name: 'Competitie Code'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
