columnSuffix: fwebvowz
contentColumnType: datetime
fieldGroup: 4361871a-c3b3-445f-8221-27814d578606 # Spelers
handle: dateOfBirth
instructions: null
name: Geboortedatum
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
