columnSuffix: berpcyhw
contentColumnType: string
fieldGroup: e27e7c24-1d05-4dcd-b1bf-8aa3a9909308 # Common
handle: email
instructions: null
name: E-mail
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
