columnSuffix: vunzosib
contentColumnType: string
fieldGroup: 4361871a-c3b3-445f-8221-27814d578606 # Spelers
handle: gender
instructions: null
name: Gender
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Man
        -
          - value
          - male
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Vrouw
        -
          - value
          - female
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Anders
        -
          - value
          - else
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
