columnSuffix: aksynypq
contentColumnType: string
fieldGroup: daf1bede-b587-43b2-bd85-b936493a1dfa # Wedstrijd
handle: matchType
instructions: null
name: 'Wedstrijd Type'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Competitie
        -
          - value
          - competition
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Vriendschappelijk
        -
          - value
          - friendly
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Beker
        -
          - value
          - cup
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
