columnSuffix: null
contentColumnType: string
fieldGroup: 596edfbc-63fe-4b5c-af4a-04bfa1df9fcb # Nieuws
handle: newsCategory
instructions: null
name: 'Nieuws Categorie'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  source: null
  sources:
    - 'section:05890c06-e285-4cae-9378-126bdadbfe23' # Nieuws Categorie
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
