columnSuffix: xmgkpzmh
contentColumnType: string
fieldGroup: 4361871a-c3b3-445f-8221-27814d578606 # Spelers
handle: playerPosition
instructions: null
name: 'Speler Positie'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Keeper
        -
          - value
          - keeper
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Verdediger
        -
          - value
          - defender
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Middenvelder
        -
          - value
          - midfielder
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Aanvaller
        -
          - value
          - attacker
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
