columnSuffix: null
contentColumnType: string
fieldGroup: 13f35aef-af9d-4c2e-b6b3-c0f6f5058ec4 # Sponsors
handle: sponsorLogo
instructions: null
name: 'Sponsor Logo'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
  restrictedLocationSubpath: sponsor/logo
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
