columnSuffix: vuvhkxeo
contentColumnType: string
fieldGroup: 5952b7af-6573-4154-99bd-98929f36de6a # Teams
handle: teamPhoto
instructions: null
name: 'Team Foto'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
  restrictedLocationSubpath: /team/foto
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:32f115a5-2b1f-4413-af1c-d9be71b0ed1f' # Public
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
