dateModified: 1676925125
email:
  fromEmail: website@irene58.nl
  fromName: 'Irene''58'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  public:
    hasUrls: true
    name: Public
    settings:
      path: /var/www/html/web/files
    type: craft\fs\Local
    url: /files
meta:
  __names__:
    0a3208f3-affb-448d-99ac-303257c1d951: Bestanden # Bestanden
    0b0c6e4f-4dfb-43e4-b758-afedf6e75fc4: 'Teams Overzicht' # Teams Overzicht
    1d006aa2-23eb-401b-8be3-1daccef1d5f8: 'Wedstrijd Type' # Wedstrijd Type
    1d343b3a-f2ac-428b-af74-acd19c271e70: 'Club Code' # Club Code
    1d686cbe-d42e-48d5-8f07-cba87b25b0af: Tekst # Tekst
    1eaed796-4f9b-402c-8de5-04e7425bc8d6: 'Hoofdmenu Item' # Hoofdmenu Item
    1eeda847-3fd9-49ad-a212-3ddaf25446c6: Adres # Adres
    02c80827-fed5-431b-81ca-ce8f5f560445: Club # Club
    2dd179ed-e08e-4084-8fff-958bc0128e83: Author # Author
    2e5fad38-e6d9-4107-b04b-755befa7a3b1: Bestuur # Bestuur
    3ec53f82-19c1-4a57-9217-fa8054c83431: Competities # Competities
    4aa67f84-30e9-4b62-82ee-90ca0bfcd617: Voornaam # Voornaam
    4b0839b9-c063-44e6-925c-6b3e38d34e08: 'Sponsors (Overzicht)' # Sponsors (Overzicht)
    5ed4d53d-47f9-4ce4-8db6-4e2ad4bc9583: 'Sponsor Logo' # Sponsor Logo
    5f1ab768-77e9-42e5-a8d1-33a51e88c0e7: 'Is Own Club?' # Is Own Club?
    5f6829e1-ccc7-4f17-af6a-d4b937db5b03: 'Wedstrijd Thuisteam' # Wedstrijd Thuisteam
    5fda7d6b-6c90-4033-b4c4-82005d425e44: Competities # Competities
    6c346423-d35b-4a69-99fe-4719f012c2da: Title # Title
    6ccb9335-6fa4-4a02-864a-960d8ff0ed1b: Achternaam # Achternaam
    6fe0bc55-379b-47e7-9a01-cd0deccba5d5: 'Wedstrijd Code' # Wedstrijd Code
    7c0938c6-ce88-4fe2-8bfe-b18d74017936: E-mail # E-mail
    7c593917-8377-4440-b9cd-e162b99fe647: Nieuws # Nieuws
    7ca18f17-7753-4baf-82da-4e7c24d3d552: Homepage # Homepage
    7db4b613-8cee-455e-835a-c0b1b1c47cfe: 'Club Logo' # Club Logo
    7f7bf0f5-26b9-4557-bcee-5585832b1522: 'Hoofd menu' # Hoofd menu
    8bc82c56-398c-4f1f-837d-30d6f59895e1: 'Speler Foto' # Speler Foto
    8db180a8-63e8-444c-b730-7f85de2e44e0: Tekst # Tekst
    8efba1fe-813b-4351-a374-091a02193857: Wedstrijd # Wedstrijd
    9a42368d-d0bf-429b-840e-38e43dd40fec: Geboortedatum # Geboortedatum
    9b381b6e-5478-41fa-a115-9c8c94c016f0: Default # Default
    09bea455-a582-4ad3-ac02-f9e42139de0a: 'Nieuws (Overzicht)' # Nieuws (Overzicht)
    9cc679be-111f-496e-8985-b4d1c111153c: Default # Default
    9dd28b29-bd55-4376-9fcf-96768a17cdf6: Afbeelding # Afbeelding
    13f35aef-af9d-4c2e-b6b3-c0f6f5058ec4: Sponsors # Sponsors
    32f115a5-2b1f-4413-af1c-d9be71b0ed1f: Public # Public
    54b0a449-36e5-4153-b4cb-653e34dab3f7: PDFs # PDFs
    73d9b7e3-8113-4470-95cb-24e658b6e41e: Afbeelding # Afbeelding
    81f7bae7-fd4d-4bf5-adf6-01f71a3da725: Button # Button
    82ea2ec9-8a62-43a4-992b-54bf0b039ac5: Menu # Menu
    92ff6d7c-52e1-4490-88ab-31b8057fa459: Embed # Embed
    97a94c06-301e-4c1c-8e07-b1eceae91ac3: Gender # Gender
    139b184d-bd3e-452b-92a6-b0cc6292373b: Default # Default
    275e4896-bf41-4955-97f0-a176d547ccf0: Default # Default
    340e0566-380f-4317-87f7-1088e327f13d: 'Nieuws (Overzicht)' # Nieuws (Overzicht)
    465d18b4-59f5-4429-9bc9-cda6a730f4a9: 'Wedstrijd Eindscore' # Wedstrijd Eindscore
    596edfbc-63fe-4b5c-af4a-04bfa1df9fcb: Nieuws # Nieuws
    632f7697-a243-4828-851e-41ad941f6c60: Default # Default
    691d5c78-9b73-4a43-8bab-85a0fb0b98be: Clubs # Clubs
    813b1092-2513-42c0-9bbc-afa50864e0bf: Telefoon # Telefoon
    863dee4e-22ab-435a-b372-6f9e6ba1f56a: PDFs # PDFs
    929ea7f4-245f-4c84-bd05-f42a969f0fcc: Default # Default
    1396ba41-9f9d-4fdb-8788-162c7d5a11a4: Spelers # Spelers
    5242e11b-4717-441a-9978-658284821328: Default # Default
    05890c06-e285-4cae-9378-126bdadbfe23: 'Nieuws Categorie' # Nieuws Categorie
    5952b7af-6573-4154-99bd-98929f36de6a: Teams # Teams
    7033b744-1ea5-4481-aeb8-7b1bfd6eae93: 'Speler Positie' # Speler Positie
    29984bc4-d676-4b9f-a3b7-3fd867b879a9: Clubs # Clubs
    86625fca-1032-46ac-adfc-ccfb6ac6adb9: Default # Default
    329395f0-8e92-45d7-8da1-d03efba44590: 'Club Route' # Club Route
    611609da-3c1c-44c7-b170-1d2c717e9e37: 'Tekstpagina''s' # Tekstpagina's
    761932df-fd3b-469b-a79a-8d7e22f5f54b: 'Irene''58' # Irene'58
    883903bb-2ced-4346-ad4a-8881b1df7f5f: Embed # Embed
    4361871a-c3b3-445f-8221-27814d578606: Spelers # Spelers
    6338189e-1976-4a2a-9705-8706b1fbd3cc: 'Bestuur (Overzicht)' # Bestuur (Overzicht)
    17851753-f1d6-4912-ae96-0e4377bab354: Inhoud # Inhoud
    30061769-c9f3-4956-8d4b-69e1540e42bf: Tekst # Tekst
    a4da36f1-92af-4214-bd7b-7cd817673b7c: Sponsors # Sponsors
    a45e8064-29dd-4fd9-9901-751b6330f738: URL # URL
    a4182423-e08b-4b3e-8b3a-3067be1e34fd: Tabel # Tabel
    ab8dd729-cd1d-408b-8a3e-f3363c079533: Afbeelding # Afbeelding
    b38b7d92-effd-4ff7-9dd7-afe36a88f42a: PDFs # PDFs
    b98c2e67-1ef7-4f68-b5db-40fd58d48d0d: 'Wedstrijd Uitteam' # Wedstrijd Uitteam
    bb8d51b0-4ea1-4f43-86f8-6141b70237da: Competities # Competities
    bf62ef32-f6a9-4a2c-b79e-dda06b88b316: Default # Default
    c74a1155-675a-48e7-a365-2c7039a357ff: Default # Default
    c91d068b-d933-4b96-ae45-6109728a4515: Homepage # Homepage
    c5644c50-0763-4e81-ba09-38cc7429b485: Quote # Quote
    c22497ae-186e-4442-8842-280f7287d053: 'Bestuur Rol' # Bestuur Rol
    ca1da903-9f47-4ac2-80f2-2bb5047f4aab: Entry # Entry
    cc10da5e-07fc-45c5-a7e0-ae91acb98128: 'Competitie Code' # Competitie Code
    cedfd60e-4cf0-4a27-9123-93a290bd8bc3: 'Entry Lijst' # Entry Lijst
    d6bd3932-17bb-492f-9ee7-2f000018ac63: 'Team Foto' # Team Foto
    d6c35615-06a5-40b0-9584-1501a0a75f32: Spelers # Spelers
    d23c1e7e-d9e0-4285-870f-3cb53df9f68c: Teams # Teams
    d345ac6c-c9b1-46d6-a195-79cb6c73bead: 'Sponsors (Overzicht)' # Sponsors (Overzicht)
    d747c871-4db7-4d98-b9b6-d903dc0f40e9: Subtitle # Subtitle
    daf1bede-b587-43b2-bd85-b936493a1dfa: Wedstrijd # Wedstrijd
    db391960-af57-43d9-9355-4557c3c45fe6: Button # Button
    ddec216d-9a35-444b-b4c7-b6b7757714fa: Bestuur # Bestuur
    dfa58418-7b57-4e09-b8a6-c598376e731a: 'Submenu Section' # Submenu Section
    dff6210f-1228-4523-8858-c711a7ff5aa6: 'Teams Overzicht' # Teams Overzicht
    e27e7c24-1d05-4dcd-b1bf-8aa3a9909308: Common # Common
    e83f5112-c8fe-4650-ae8a-56c5026d013d: 'Bestuur (Overzicht)' # Bestuur (Overzicht)
    eb171182-2d0a-4720-86fe-620c701edf2f: 'Nieuws Categorie' # Nieuws Categorie
    ee744fd9-b67b-477f-8578-1bd70260f68e: Content # Content
    f67f9e31-79ca-4013-8959-ec0e19edbd19: 'Team Code' # Team Code
    fb0ab934-e102-4306-b8a8-e5f6598a60ef: 'Irene''58' # Irene'58
    fdbaeb5e-2953-4ec6-83c6-67ba0ac88bbc: 'Wedstrijd Datum' # Wedstrijd Datum
plugins:
  craft-webpme:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  express-forms:
    edition: lite
    enabled: true
    schemaVersion: 1.0.2
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  linkit:
    edition: standard
    enabled: true
    licenseKey: DOGUIQIWHYWU2YYFOMIR3ZTZ
    schemaVersion: 1.2.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage:
        - '14'
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ siteName }}'
      titleSuffix: null
      twitterHandle: ''
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Irene''58'
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: Europe/Amsterdam
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
