defaultPlacement: end
enableVersioning: true
handle: boardMembers
name: Bestuur
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 2b70b8e4-3142-4389-9214-ac3b0e224b89
type: structure
