defaultPlacement: end
enableVersioning: true
handle: clubs
name: Clubs
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 99111f31-7eba-40c9-828c-34ae0d4e7e91
type: structure
