defaultPlacement: end
enableVersioning: true
handle: competitions
name: Competities
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 7e44055a-49e4-4336-b29b-0079b50a80fe
type: structure
