defaultPlacement: end
enableVersioning: true
handle: mainMenu
name: 'Hoofd menu'
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 06b5bbb4-e5e9-4675-bdb7-bab56403a72e
type: structure
