defaultPlacement: end
enableVersioning: true
handle: matches
name: Wedstrijd
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f6e26508-ff11-436e-903e-c301c6acbf21
type: structure
