defaultPlacement: end
enableVersioning: true
handle: news
name: Nieuws
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: true
    template: nieuws/_entry
    uriFormat: 'nieuws/{slug}'
type: channel
