defaultPlacement: end
enableVersioning: true
handle: newsCategory
name: 'Nieuws Categorie'
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 1954b56c-d55e-43fd-937f-2cf5f4de763b
type: structure
