defaultPlacement: end
enableVersioning: true
handle: players
name: Spelers
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 231d97e0-8ae6-45ff-9b36-fb6113e49919
type: structure
