defaultPlacement: end
enableVersioning: true
handle: sponsors
name: Sponsors
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 484afc98-b6b3-474d-a80f-30420bdecfc9
type: structure
