defaultPlacement: end
enableVersioning: true
handle: teams
name: Teams
propagationMethod: all
siteSettings:
  fb0ab934-e102-4306-b8a8-e5f6598a60ef: # Irene'58
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 65ee6f9a-a141-4dbf-81dc-1ba8a9e4f656
type: structure
